fd

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -13,8 +13,8 @@ jobs:
     runs-on: ubuntu-latest
     environment: |-
       ${{
-        github.ref_name == 'main' && 'production'
-        || github.ref_name == 'staging' && 'staging'
+        github.base_ref == 'main' && 'production'
+        || github.base_ref == 'staging' && 'staging'
         || 'development'
       }}
     env:
@@ -26,138 +26,138 @@ jobs:
       # run
         # working-directory: terragrunt/modules/
     steps:
+      - run: echo "${{ github.base_ref }}"
+      - run: |-
+          echo '${{
+            github.base_ref == 'main' && 'production'
+            || github.base_ref == 'staging' && 'staging'
+            || 'development'
+          }}'
+      - run: echo '${{ toJson(github) }}'
+        # Setup
+      - uses: hashicorp/setup-terraform@v3
+      - uses: autero1/action-terragrunt@v1.3.2
+        with:
+          terragrunt_version: latest
+      - uses: terraform-linters/setup-tflint@v4
+      - uses: shmokmt/actions-setup-tfcmt@v2
 
-    - run: |-
-        echo '${{
-          github.ref_name == 'main' && 'production'
-          || github.ref_name == 'staging' && 'staging'
-          || 'development'
-        }}'
-    - run: echo '${{ toJson(github) }}'
-      # Setup
-    - uses: hashicorp/setup-terraform@v3
-    - uses: autero1/action-terragrunt@v1.3.2
-      with:
-        terragrunt_version: latest
-    - uses: terraform-linters/setup-tflint@v4
-    - uses: shmokmt/actions-setup-tfcmt@v2
+      # Checkout
+      - name: Checkout target branch
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }}
 
-    # Checkout
-    - name: Checkout target branch
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.head_ref }}
+      # AWS Credential
+      - name: Set up AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-northeast-1
 
-    # AWS Credential
-    - name: Set up AWS credentials
-      uses: aws-actions/configure-aws-credentials@v2
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ap-northeast-1
+      - name: Render terraform docs and push changes back to PR
+        id: terraform-docs
+        uses: terraform-docs/gh-actions@main
+        with:
+          find-dir: terragrunt/modules/
+          output-file: README.md
+          output-method: inject
+          git-push: true
+          git-commit-message: update terraform docs
 
-    - name: Render terraform docs and push changes back to PR
-      id: terraform-docs
-      uses: terraform-docs/gh-actions@main
-      with:
-        find-dir: terragrunt/modules/
-        output-file: README.md
-        output-method: inject
-        git-push: true
-        git-commit-message: update terraform docs
+      - name: Terraform Format
+        id: fmt
+        uses: gh640/command-result-action@v1
+        with:
+          command: terraform fmt -check -recursive -diff
+          cwd: terragrunt/modules/
+        continue-on-error: true
 
-    - name: Terraform Format
-      id: fmt
-      uses: gh640/command-result-action@v1
-      with:
-        command: terraform fmt -check -recursive -diff
-        cwd: terragrunt/modules/
-      continue-on-error: true
+      - name: Terraform validate
+        id: validate
+        uses: gh640/command-result-action@v1
+        with:
+          command: terragrunt run-all validate --terragrunt-no-color -no-color
+          cwd: terragrunt/envs/dev/
+        continue-on-error: true
 
-    - name: Terraform validate
-      id: validate
-      uses: gh640/command-result-action@v1
-      with:
-        command: terragrunt run-all validate --terragrunt-no-color -no-color
-        cwd: terragrunt/envs/dev/
-      continue-on-error: true
+      - name: Terraform init
+        id: init
+        uses: gh640/command-result-action@v1
+        with:
+          command: terragrunt run-all init --terragrunt-no-color -no-color
+          cwd: terragrunt/envs/dev/
+        continue-on-error: true
 
-    - name: Terraform init
-      id: init
-      uses: gh640/command-result-action@v1
-      with:
-        command: terragrunt run-all init --terragrunt-no-color -no-color
-        cwd: terragrunt/envs/dev/
-      continue-on-error: true
+      # - name: Run TFLint
+      #   id: tflint
+      #   uses: gh640/command-result-action@v1
+      #   with:
+      #     command: tflint --recursive --format compact
+      #     cwd: terragrunt/modules/
+      #   continue-on-error: true
+      # - run: |
+      #     echo "${{ steps.tflint.outputs.stdout }}"
+      #     echo "${{ steps.tflint.outputs.stderr }}" >&2
 
-    # - name: Run TFLint
-    #   id: tflint
-    #   uses: gh640/command-result-action@v1
-    #   with:
-    #     command: tflint --recursive --format compact
-    #     cwd: terragrunt/modules/
-    #   continue-on-error: true
-    # - run: |
-    #     echo "${{ steps.tflint.outputs.stdout }}"
-    #     echo "${{ steps.tflint.outputs.stderr }}" >&2
+      - name: Run TFLint
+        id: tflint
+        run: |
+          echo "TFLINT_RESULT<<ENND" >> $GITHUB_ENV
+          tflint --recursive --format compact 2>&1 >> $GITHUB_ENV || TFLINT_FAILED=1
+          echo "ENND" >> $GITHUB_ENV
+          echo "TFLINT_FAILED=$TFLINT_FAILED" >> $GITHUB_ENV
+        continue-on-error: true
+      - run: for line in "${{ env.TFLINT_RESULT }}"; do echo "$line"; done
 
-    - name: Run TFLint
-      id: tflint
-      run: |
-        echo "TFLINT_RESULT<<ENND" >> $GITHUB_ENV
-        tflint --recursive --format compact 2>&1 >> $GITHUB_ENV || TFLINT_FAILED=1
-        echo "ENND" >> $GITHUB_ENV
-        echo "TFLINT_FAILED=$TFLINT_FAILED" >> $GITHUB_ENV
-      continue-on-error: true
-    - run: for line in "${{ env.TFLINT_RESULT }}"; do echo "$line"; done
+      - name: PR comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        # env:
+        #   TFLINT_RESULT2: ${{ env.TFLINT_RESULT }}
+        with:
+          header: terraform
+          hide_and_recreate: true
+          # hide: true
+          hide_classify: "OUTDATED"
+          message: |
+            ${{ steps.terraform-docs.outputs.num_changed > 0 && '✅' || '➖' }} terraform docs (number of updated = ${{ steps.terraform-docs.outputs.num_changed }})
+            <details>
+            <summary>${{ steps.fmt.outputs.exitCode == 0 && '✅' || '❌' }} terraform fmt</summary>
 
-    - name: PR comment
-      uses: marocchino/sticky-pull-request-comment@v2
-      # env:
-      #   TFLINT_RESULT2: ${{ env.TFLINT_RESULT }}
-      with:
-        header: terraform
-        hide_and_recreate: true
-        # hide: true
-        hide_classify: "OUTDATED"
-        message: |
-          ${{ steps.terraform-docs.outputs.num_changed > 0 && '✅' || '➖' }} terraform docs (number of updated = ${{ steps.terraform-docs.outputs.num_changed }})
-          <details>
-          <summary>${{ steps.fmt.outputs.exitCode == 0 && '✅' || '❌' }} terraform fmt</summary>
+            ```diff
+            ${{ steps.fmt.outputs.stderr }}${{ steps.fmt.outputs.stdout }}
+            ```
 
-          ```diff
-          ${{ steps.fmt.outputs.stderr }}${{ steps.fmt.outputs.stdout }}
-          ```
+            </details>
+            <details>
+            <summary>${{ steps.init.outputs.exitCode == 0 && '✅' || '❌' }} terraform init</summary>
 
-          </details>
-          <details>
-          <summary>${{ steps.init.outputs.exitCode == 0 && '✅' || '❌' }} terraform init</summary>
+            ```
+            ${{ steps.init.outputs.stderr }}${{ steps.init.outputs.stdout }}
+            ```
 
-          ```
-          ${{ steps.init.outputs.stderr }}${{ steps.init.outputs.stdout }}
-          ```
+            </details>
+            <details>
+            <summary>${{ steps.validate.outputs.exitCode == 0 && '✅' || '❌' }} terraform validate</summary>
 
-          </details>
-          <details>
-          <summary>${{ steps.validate.outputs.exitCode == 0 && '✅' || '❌' }} terraform validate</summary>
+            ```
+            ${{ steps.validate.outputs.stderr }}${{ steps.validate.outputs.stdout }}
+            ```
 
-          ```
-          ${{ steps.validate.outputs.stderr }}${{ steps.validate.outputs.stdout }}
-          ```
+            </details>
+            <details>
+            <summary>${{ env.TFLINT_FAILED != 1 && '✅' || '❌' }} terraform tflint</summary>
 
-          </details>
-          <details>
-          <summary>${{ env.TFLINT_FAILED != 1 && '✅' || '❌' }} terraform tflint</summary>
+            ```
+            ${{ env.TFLINT_RESULT }}
+            ```
 
-          ```
-          ${{ env.TFLINT_RESULT }}
-          ```
+            </details>
 
-          </details>
-
-    - name: Terragrunt plan
-      working-directory: terragrunt/
-      # env:
-      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        terragrunt run-all plan --terragrunt-tfpath ${GITHUB_WORKSPACE}/.github/scripts/tfwrapper.sh
+      - name: Terragrunt plan
+        working-directory: terragrunt/
+        # env:
+        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          terragrunt run-all plan --terragrunt-tfpath ${GITHUB_WORKSPACE}/.github/scripts/tfwrapper.sh
