fd

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -90,9 +90,8 @@ jobs:
       id: tflint
       run: |
         echo "TFLINT_RESULT<<ENND" >> $GITHUB_ENV
-        tflint --recursive --format compact 2>&1 >> $GITHUB_ENV || result=$? || true
+        tflint --recursive --format compact 2>&1 >> $GITHUB_ENV || echo "TFLINT_FAILED=1" >> $GITHUB_ENV
         echo "ENND" >> $GITHUB_ENV
-        echo "TFLINT_EXITCODE=$result" >> $GITHUB_ENV
       continue-on-error: true
     # - run: echo '${{ toJson(steps.tflint) }}'
     - run: for line in "${{ env.TFLINT_RESULT }}"; do echo "$line"; done
@@ -136,7 +135,7 @@ jobs:
 
           </details>
           <details>
-          <summary>${{ env.TFLINT_EXITCODE == 0 && '✅' || '❌' }} terraform tflint</summary>
+          <summary>${{ env.TFLINT_FAILED != 1 && '✅' || '❌' }} terraform tflint</summary>
 
           ```
           ${{ env.TFLINT_RESULT }}
